/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tpo5;

import Clases_De_Uso.Alimentos;
import Clases_De_Uso.Electrodomestico;
import Clases_De_Uso.OrdenN;
import Clases_De_Uso.OrdenP;
import Clases_De_Uso.Ropa;
import Clases_De_Uso.Super_Clase;
import Menus_Productos.Interno;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DANIELALEJANDROMIRAN
 */
//Nombre: Daniel Miranda Alejandro - DNI: 45800784.
public class TPO5_Ejercicio extends javax.swing.JFrame {
    private static ArrayList<Super_Clase> Prod = new ArrayList();
    private static ArrayList<Ropa> Ropita = new ArrayList(); private static ArrayList<Alimentos> comestibles = new ArrayList(); private static ArrayList<Electrodomestico> electro = new ArrayList();
    DefaultTableModel Prueba = new DefaultTableModel();
    Interno Intern1 = new Interno(this,true);
    
    /**
     * Creates new form TPO5_Ejercicio
     */
    public TPO5_Ejercicio() {
        initComponents();
        String[] Cl = {"Producto","Categoria","Precio"};
        Prueba.setColumnIdentifiers(Cl);
        Productos.setModel(Prueba);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Combito = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Productos = new javax.swing.JTable();
        Evento = new javax.swing.JButton();
        JActualizar = new javax.swing.JButton();
        Orden = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuperMayorista");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 140, 22));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));

        Combito.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Combito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentos", "Electrodomesticos", "Ropa" }));
        Combito.setBorder(new javax.swing.border.MatteBorder(null));

        Productos.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item_1", "Item_2", "Item_3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Productos.setColumnSelectionAllowed(true);
        Productos.setShowGrid(true);
        Productos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Productos);
        Productos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (Productos.getColumnModel().getColumnCount() > 0) {
            Productos.getColumnModel().getColumn(0).setResizable(false);
            Productos.getColumnModel().getColumn(1).setResizable(false);
            Productos.getColumnModel().getColumn(2).setResizable(false);
        }

        Evento.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Evento.setText("Agregar Producto");
        Evento.setBorder(new javax.swing.border.MatteBorder(null));
        Evento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EventoMouseClicked(evt);
            }
        });

        JActualizar.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        JActualizar.setText("Actualizar");
        JActualizar.setBorder(new javax.swing.border.MatteBorder(null));
        JActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JActualizarActionPerformed(evt);
            }
        });

        Orden.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Orden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Precio", "Remover" }));
        Orden.setToolTipText("Otro Menu");
        Orden.setBorder(new javax.swing.border.MatteBorder(null));
        Orden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jButton1.setText("Ordenar por:");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Evento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Combito, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Orden, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Evento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Combito, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(Orden)
                    .addComponent(JActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EventoMouseClicked
        if(Intern1.isVisible()==false){
            Intern1.setVisible(true);
        }
    }//GEN-LAST:event_EventoMouseClicked

    private void JActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JActualizarActionPerformed
        for(int i=0;i<Prueba.getRowCount();){
            Prueba.removeRow(i);
        }
        switch((String) Combito.getSelectedItem()){
            case ("Ropa"):
                
                
                for(Ropa R1: Ropita){
                    Prueba.addRow(new Object[]{R1.getNombre_Producto(),R1.getCategoria(),R1.getPrecio()});
                }
                Productos.setModel(Prueba);
                break;
            case ("Alimentos"):
                
                for(Alimentos A1: comestibles){
                    Prueba.addRow(new Object[]{A1.getNombre_Producto(),A1.getCategoria(),A1.getPrecio()});
                }
                Productos.setModel(Prueba);
                break;
            case ("Electrodomesticos"):
                
                for(Electrodomestico E1: electro){
                    Prueba.addRow(new Object[]{E1.getNombre_Producto(),E1.getCategoria(),E1.getPrecio()});
                }
                Productos.setModel(Prueba);
                break;
        }
        
    }//GEN-LAST:event_JActualizarActionPerformed

    private void OrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenActionPerformed
        switch((String)Orden.getSelectedItem()){
            case ("Nombre"):
                switch ((String) Combito.getSelectedItem()){
                    case ("Alimentos"):
                        Collections.sort(comestibles, new OrdenN());
                        break;
                    case ("Electrodomesticos"):
                        Collections.sort(electro, new OrdenN());
                        break;
                    case ("Ropa"):
                        Collections.sort(Ropita, new OrdenN());
                        break;
                }
                break;
            case ("Precio"):
                switch ((String) Combito.getSelectedItem()){
                    case ("Alimentos"):
                        Collections.sort(comestibles, new OrdenP());
                        break;
                    case ("Electrodomesticos"):
                        Collections.sort(electro, new OrdenP());
                        break;
                    case ("Ropa"):
                        Collections.sort(Ropita, new OrdenP());
                        break;
                }
                break;
        }
    }//GEN-LAST:event_OrdenActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPO5_Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPO5_Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPO5_Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPO5_Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPO5_Ejercicio().setVisible(true);
            }
        });
    }

    public static ArrayList<Super_Clase> getProd() {
        return Prod;
    }

    public static ArrayList<Ropa> getRopita() {
        return Ropita;
    }

    public static ArrayList<Alimentos> getComestibles() {
        return comestibles;
    }

    public static ArrayList<Electrodomestico> getElectro() {
        return electro;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combito;
    private javax.swing.JButton Evento;
    private javax.swing.JButton JActualizar;
    private javax.swing.JComboBox<String> Orden;
    private javax.swing.JTable Productos;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
